# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T17:13:05+00:00

from __future__ import annotations

from enum import Enum


class IncidentType(Enum):
    crash = 'crash'
    hazard = 'hazard'
    theft = 'theft'
    unconfirmed = 'unconfirmed'
    infrastructure_issue = 'infrastructure_issue'
    chop_shop = 'chop_shop'
